"""Shared DHE client timing and sizing constants."""

from __future__ import annotations

COMMAND_RETRY_ATTEMPTS = 2
COMMAND_RETRY_DELAY_SECONDS = 1.0
DEFAULT_NOMINAL_POWER_KW = 24.0
AUTH_POLL_TIMEOUT_SECONDS = 10.0
COMMAND_CONFIRMATION_TIMEOUT = 12.0
COMMAND_READBACK_INTERVAL = 1.0
ODB_READBACK_REQUEST_WINDOW_SECONDS = 30.0
APP_COMMAND_CONFIRMATION_TIMEOUT = 3.0
WEATHER_CATALOG_TIMEOUT = 8.0
RUNTIME_STARTUP_PROOF_TIMEOUT_SECONDS = 10.0
CLIENT_MODULE_MAX_BYTES = 50 * 1024
