"""Shared dynamic payload type aliases for DHE app catalogs."""

from __future__ import annotations

from typing import Any, TypeAlias, TypedDict

# Radio and weather payloads are generated by the DHE web application API and
# vary across catalogs and firmware. Keep the concrete value shape dynamic, but
# name the payload boundaries so flow/service code does not spread anonymous
# dict[str, Any] contracts.

JSONScalar: TypeAlias = str | int | float | bool | None
JSONValue: TypeAlias = JSONScalar | dict[str, Any] | list[Any]


class WeatherNamePayload(TypedDict, total=False):
    """Localized weather location name entry from DHE payloads."""

    Name: str
    Language: str
    SearchType: int | str


class WeatherLocationShape(TypedDict, total=False):
    """Weather location payload used across favorites, search and selection."""

    LocationId: int | str
    Name: str
    Country: str
    CountryId: int | str
    SearchType: int | str
    IntNames: list[WeatherNamePayload]
    I18nNames: list[WeatherNamePayload]


class WeatherCountryShape(TypedDict, total=False):
    """Weather country payload exposed by DHE catalogs."""

    Id: int | str
    CountryId: int | str
    Name: str
    Code: str


class RadioStationShape(TypedDict, total=False):
    """Radio station payload used for favorites, search and selection."""

    Id: int | str
    Name: str
    Genre: str
    Language: str
    Country: str


# Keep payload aliases dynamic for compatibility with runtime and existing
# service/config-flow contracts. The more precise TypedDict shapes above are
# available for future gradual typing where list invariance does not break
# existing signatures.
WeatherCountryPayload: TypeAlias = dict[str, Any]
WeatherLocationPayload: TypeAlias = dict[str, Any]
RadioStationPayload: TypeAlias = dict[str, Any]
