"""Shared dynamic payload type aliases for DHE app catalogs."""

from __future__ import annotations

from typing import Any, TypeAlias

# Radio and weather payloads are generated by the DHE web application API and
# vary across catalogs and firmware. Keep the concrete value shape dynamic, but
# name the payload boundaries so flow/service code does not spread anonymous
# dict[str, Any] contracts.
WeatherCountryPayload: TypeAlias = dict[str, Any]
WeatherLocationPayload: TypeAlias = dict[str, Any]
RadioStationPayload: TypeAlias = dict[str, Any]
